backend:
  batch_size: 10
  batch_size_reduction: 'True'
  batch_size_reduction_factor: 2
  display_step: 50
  evaluator: tensorpot
  gpu_config:
    mem_limit: 0
cutoff: 7
data:
  filename: /home/tomasz/Documents/MLIP_Pt-111_CH4/hyperparameters_opt/df_full.pckl.gzip
  reference_energy: auto
  test_filename: /home/tomasz/Documents/MLIP_Pt-111_CH4/hyperparameters_opt/df_test.pckl.gzip
fit:
  loss:
    L1_coeffs: 1.0e-08
    L2_coeffs: 1.0e-08
    kappa: auto
    w0_rad: 1.0e-08
    w1_coeffs: 0
    w1_rad: 1.0e-08
    w2_coeffs: 0
    w2_rad: 1.0e-08
  maxiter: 10
  optimizer: BFGS
  repulsion: auto
  trainable_parameters: ALL
metadata:
  purpose: Potential fit
potential:
  bonds:
    (C, H):
      NameOfCutoffFunction: cos
      dcut: 0.07818940902700418
      radbase: SBessel
      radparameters:
      - 2.6509131087954745
      rcut: 1.09
    ALL:
      NameofCutoffFunction: cos
      dcut: 0.01089751666598229
      radbase: SBessel
      radparameters:
      - 6.371651421518384
      rcut: 3.2291637642679563
  deltaSplineBins: 0.001
  elements:
  - Pt
  - C
  - H
  embeddings:
    ALL:
      drho_core_cut: 500
      fs_parameters:
      - 1
      - 1
      - 1
      - 0.5
      ndensity: 2
      npot: FinnisSinclairShiftedScaled
      rho_core_cut: 3000
  functions:
    ALL:
      lmax_by_orders:
      - 0
      - 3
      - 2
      - 1
      nradmax_by_orders:
      - 15
      - 3
      - 2
      - 1
    number_of_functions_per_element: 838
seed: 42
